"""
Rappi operational metric dictionary.

Canonical definitions for all 13 metrics tracked across the 9 LATAM markets,
enriched with scale metadata so the LLM and tool handlers can interpret values
correctly (e.g., proportion 0-1 vs monetary vs unbounded ratio).

Exposes:
    MetricInfo      — TypedDict describing one metric
    METRIC_DICTIONARY: dict[str, MetricInfo]  — metric_name -> full info
    get_metric_info(name) -> MetricInfo | None
"""

from __future__ import annotations

from typing import Literal, TypedDict


class MetricInfo(TypedDict):
    description: str
    scale: Literal["proportion", "monetary", "ratio_unbounded"]
    scale_note: str


METRIC_DICTIONARY: dict[str, MetricInfo] = {
    "% PRO Users Who Breakeven": {
        "description": (
            "Users with an active Pro subscription whose generated value for the company "
            "has covered the full cost of their membership, divided by the total number of Pro users. "
            "A higher rate indicates that the Pro program is economically self-sustaining."
        ),
        "scale": "proportion",
        "scale_note": "Proporción entre 0 y 1 (puede representarse como porcentaje 0%–100%).",
    },
    "% Restaurants Sessions With Optimal Assortment": {
        "description": (
            "Sessions in which the user was exposed to a minimum of 40 restaurants, "
            "divided by the total number of sessions in the Restaurants vertical. "
            "Measures whether supply depth is sufficient to give users meaningful choice."
        ),
        "scale": "proportion",
        "scale_note": "Proporción entre 0 y 1 (puede representarse como porcentaje 0%–100%).",
    },
    "Gross Profit UE": {
        "description": (
            "Gross profit per order (Unit Economics): gross margin generated by the company "
            "divided by the total number of orders. A key profitability indicator at the "
            "order level."
        ),
        "scale": "monetary",
        "scale_note": (
            "Valor monetario por orden (margen bruto). Puede ser negativo. "
            "NO es una proporción. Rango observado: [-97, 13] aprox."
        ),
    },
    "Lead Penetration": {
        "description": (
            "Stores currently enabled on Rappi divided by the total addressable market "
            "(Leads + Enabled Stores + Churned Stores). Measures how much of the potential "
            "merchant base has been onboarded."
        ),
        "scale": "ratio_unbounded",
        "scale_note": (
            "Ratio que por definición puede exceder 1.0 cuando el denominador "
            "(leads + habilitadas + salidas) es menor que el numerador. "
            "Valores altos no son error."
        ),
    },
    "MLTV Top Verticals Adoption": {
        "description": (
            "Users who have placed orders across multiple top verticals (restaurants, super, "
            "pharmacy, liquors) divided by the total number of Rappi users. Tracks multi-vertical "
            "engagement, a strong predictor of long-term user value (MLTV)."
        ),
        "scale": "proportion",
        "scale_note": "Proporción entre 0 y 1 (puede representarse como porcentaje 0%–100%).",
    },
    "Non-Pro PTC > OP": {
        "description": (
            "Conversion rate of non-Pro users from 'Proceed to Checkout' (PTC) to 'Order Placed' "
            "(OP). Measures checkout friction for users without a Pro subscription."
        ),
        "scale": "proportion",
        "scale_note": "Proporción entre 0 y 1 (puede representarse como porcentaje 0%–100%).",
    },
    "Perfect Orders": {
        "description": (
            "Orders completed without any cancellation, defect, or significant delay, divided by "
            "the total number of orders. The primary quality-of-service metric."
        ),
        "scale": "proportion",
        "scale_note": "Proporción entre 0 y 1 (puede representarse como porcentaje 0%–100%).",
    },
    "Pro Adoption": {
        "description": (
            "Users with an active Pro subscription divided by the total number of Rappi users "
            "in the market. Measures penetration of the subscription program."
        ),
        "scale": "proportion",
        "scale_note": "Proporción entre 0 y 1 (puede representarse como porcentaje 0%–100%).",
    },
    "Restaurants Markdowns / GMV": {
        "description": (
            "Total discount value applied to restaurant orders divided by the Gross Merchandise "
            "Value (GMV) of restaurant orders. Tracks promotional intensity in the Restaurants vertical."
        ),
        "scale": "proportion",
        "scale_note": "Proporción entre 0 y 1 (puede representarse como porcentaje 0%–100%).",
    },
    "Restaurants SS > ATC CVR": {
        "description": (
            "Conversion rate in the Restaurants vertical from 'Select Store' (SS) to "
            "'Add to Cart' (ATC). Measures how well the in-store experience converts browsing "
            "into purchase intent."
        ),
        "scale": "proportion",
        "scale_note": "Proporción entre 0 y 1 (puede representarse como porcentaje 0%–100%).",
    },
    "Restaurants SST > SS CVR": {
        "description": (
            "Percentage of users who, after selecting the 'Restaurants' vertical (SST), "
            "proceed to select a specific store (SS). Measures the effectiveness of the "
            "restaurant catalog in driving store selection."
        ),
        "scale": "proportion",
        "scale_note": "Proporción entre 0 y 1 (puede representarse como porcentaje 0%–100%).",
    },
    "Retail SST > SS CVR": {
        "description": (
            "Percentage of users who, after selecting the 'Supermercados' vertical (SST), "
            "proceed to select a specific store (SS). The retail equivalent of the restaurant "
            "funnel metric above."
        ),
        "scale": "proportion",
        "scale_note": "Proporción entre 0 y 1 (puede representarse como porcentaje 0%–100%).",
    },
    "Turbo Adoption": {
        "description": (
            "Users who have placed at least one order through the Turbo channel (ultra-fast "
            "delivery) divided by the total number of users with Turbo availability in their zone. "
            "Measures Turbo channel penetration among eligible users."
        ),
        "scale": "proportion",
        "scale_note": "Proporción entre 0 y 1 (puede representarse como porcentaje 0%–100%).",
    },
}

# Raw data stores this metric under a longer name; map both so lookups never fail.
_ALIASES: dict[str, str] = {
    "Pro Adoption (Last Week Status)": "Pro Adoption",
}


def get_metric_info(metric_name: str) -> MetricInfo | None:
    """Return metric info or None if not found. Handles the 'Pro Adoption' rename."""
    canonical = _ALIASES.get(metric_name, metric_name)
    return METRIC_DICTIONARY.get(canonical)
