"""
Rappi operational metric dictionary.

Canonical definitions for all 13 metrics tracked across the 9 LATAM markets.
Inject these definitions into the system prompt so the LLM understands what
each metric means and can map business questions to the correct tool calls.

Exposes:
    METRIC_DICTIONARY: dict[str, str]  — metric_name -> definition
"""

from __future__ import annotations

METRIC_DICTIONARY: dict[str, str] = {
    "% PRO Users Who Breakeven": (
        "Users with an active Pro subscription whose generated value for the company "
        "has covered the full cost of their membership, divided by the total number of Pro users. "
        "A higher rate indicates that the Pro program is economically self-sustaining."
    ),
    "% Restaurants Sessions With Optimal Assortment": (
        "Sessions in which the user was exposed to a minimum of 40 restaurants, "
        "divided by the total number of sessions in the Restaurants vertical. "
        "Measures whether supply depth is sufficient to give users meaningful choice."
    ),
    "Gross Profit UE": (
        "Gross profit per order (Unit Economics): gross margin generated by the company "
        "divided by the total number of orders. A key profitability indicator at the "
        "order level."
    ),
    "Lead Penetration": (
        "Stores currently enabled on Rappi divided by the total addressable market "
        "(Leads + Enabled Stores + Churned Stores). Measures how much of the potential "
        "merchant base has been onboarded."
    ),
    "MLTV Top Verticals Adoption": (
        "Users who have placed orders across multiple top verticals (restaurants, super, "
        "pharmacy, liquors) divided by the total number of Rappi users. Tracks multi-vertical "
        "engagement, a strong predictor of long-term user value (MLTV)."
    ),
    "Non-Pro PTC > OP": (
        "Conversion rate of non-Pro users from 'Proceed to Checkout' (PTC) to 'Order Placed' "
        "(OP). Measures checkout friction for users without a Pro subscription."
    ),
    "Perfect Orders": (
        "Orders completed without any cancellation, defect, or significant delay, divided by "
        "the total number of orders. The primary quality-of-service metric."
    ),
    "Pro Adoption": (
        "Users with an active Pro subscription divided by the total number of Rappi users "
        "in the market. Measures penetration of the subscription program."
    ),
    "Restaurants Markdowns / GMV": (
        "Total discount value applied to restaurant orders divided by the Gross Merchandise "
        "Value (GMV) of restaurant orders. Tracks promotional intensity in the Restaurants vertical."
    ),
    "Restaurants SS > ATC CVR": (
        "Conversion rate in the Restaurants vertical from 'Select Store' (SS) to "
        "'Add to Cart' (ATC). Measures how well the in-store experience converts browsing "
        "into purchase intent."
    ),
    "Restaurants SST > SS CVR": (
        "Percentage of users who, after selecting the 'Restaurants' vertical (SST), "
        "proceed to select a specific store (SS). Measures the effectiveness of the "
        "restaurant catalog in driving store selection."
    ),
    "Retail SST > SS CVR": (
        "Percentage of users who, after selecting the 'Supermercados' vertical (SST), "
        "proceed to select a specific store (SS). The retail equivalent of the restaurant "
        "funnel metric above."
    ),
    "Turbo Adoption": (
        "Users who have placed at least one order through the Turbo channel (ultra-fast "
        "delivery) divided by the total number of users with Turbo availability in their zone. "
        "Measures Turbo channel penetration among eligible users."
    ),
}
